-- Sharma Interior Construction - Supabase schema + content
-- Generated from data/site.db by scratchpad/gen_schema.py
--
-- Paste this whole file into the Supabase SQL Editor and run it.
-- Safe to re-run: it drops and recreates the content tables.
-- Admin logins are NOT here - Supabase Auth handles those.

begin;

drop table if exists public.redirects, public.media, public.page_seo, public.jobs, public.faqs, public.testimonials, public.team, public.projects, public.services, public.settings cascade;

create table public.settings (
  "key" text,
  "value" text default '' not null,
  primary key ("key")
);

create table public.services (
  "id" bigint generated by default as identity primary key,
  "slug" text not null unique,
  "title" text not null,
  "description" text default '' not null,
  "icon" text default '' not null,
  "image" text default '' not null,
  "features" text default '[]' not null,
  "sort" integer default 0 not null,
  "active" boolean default true not null,
  "featured" boolean default false not null
);

create table public.projects (
  "id" bigint generated by default as identity primary key,
  "slug" text not null unique,
  "title" text not null,
  "location" text default '' not null,
  "category" text default 'residential' not null,
  "status" text default 'completed' not null,
  "completion" text default '' not null,
  "description" text default '' not null,
  "image" text default '' not null,
  "sort" integer default 0 not null,
  "active" boolean default true not null,
  "featured" boolean default false not null
);

create table public.team (
  "id" bigint generated by default as identity primary key,
  "name" text not null,
  "role" text default '' not null,
  "bio" text default '' not null,
  "image" text default '' not null,
  "linkedin" text default '' not null,
  "email" text default '' not null,
  "sort" integer default 0 not null,
  "active" boolean default true not null
);

create table public.testimonials (
  "id" bigint generated by default as identity primary key,
  "name" text not null,
  "company" text default '' not null,
  "quote" text default '' not null,
  "rating" integer default 5 not null,
  "image" text default '' not null,
  "sort" integer default 0 not null,
  "active" boolean default true not null
);

create table public.faqs (
  "id" bigint generated by default as identity primary key,
  "question" text default '' not null,
  "answer" text default '' not null,
  "page" text default '/contact.html' not null,
  "sort" integer default 0 not null,
  "active" boolean default true not null
);

create table public.jobs (
  "id" bigint generated by default as identity primary key,
  "title" text not null,
  "location" text default '' not null,
  "experience" text default '' not null,
  "employment" text default 'Full time' not null,
  "description" text default '' not null,
  "sort" integer default 0 not null,
  "active" boolean default true not null,
  "created_at" timestamptz default now() not null
);

create table public.page_seo (
  "route" text,
  "title" text default '' not null,
  "description" text default '' not null,
  "keyword" text default '' not null,
  "og_title" text default '' not null,
  "og_desc" text default '' not null,
  "og_image" text default '' not null,
  "canonical" text default '' not null,
  "noindex" boolean default false not null,
  "nofollow" boolean default false not null,
  "changefreq" text default 'monthly' not null,
  "priority" text default '0.7' not null,
  "updated_at" timestamptz default now() not null,
  primary key ("route")
);

create table public.media (
  "id" bigint generated by default as identity primary key,
  "filename" text not null,
  "path" text not null,
  "width" integer default 0 not null,
  "height" integer default 0 not null,
  "bytes" integer default 0 not null,
  "created_at" timestamptz default now() not null
);

create table public.redirects (
  "id" bigint generated by default as identity primary key,
  "from_path" text not null unique,
  "to_path" text not null,
  "hits" integer default 0 not null,
  "created_at" timestamptz default now() not null
);

-- ------------------------------------------------------------------
-- content
-- ------------------------------------------------------------------

-- settings (52 rows)
insert into public.settings ("key", "value") values
  ('site_name', 'Sharma Interior Construction'),
  ('tagline', 'We Build Landmarks That Last Generations'),
  ('hero_heading', 'We Build <em>Landmarks</em><br>That Last Generations'),
  ('hero_text', 'From residential towers to industrial plants and public infrastructure - Sharma Interior Construction delivers projects on time, on budget and to specification, with safety built into every stage.'),
  ('hero_image', 'homeback.jpg'),
  ('about_heading', 'A Contractor Built On Engineering Discipline'),
  ('about_text', 'Founded on a simple principle - do the work properly the first time - Sharma Interior Construction has grown into a full-service contractor delivering across residential, commercial, industrial and infrastructure sectors.'),
  ('about_image', 'cc.jpg'),
  ('mission', 'To deliver construction that performs for decades - built to specification, handed over on programme, and priced without games.'),
  ('vision', 'To be the contractor clients call first because the last project went right, not because we were the cheapest bid on the table.'),
  ('values', 'Safety before schedule. Accuracy before speed. Straight answers before comfortable ones. Ownership of our mistakes.'),
  ('stat_years', '10'),
  ('stat_projects', '1500'),
  ('stat_clients', '790'),
  ('stat_workforce', '450'),
  ('phone', '+91 98765 43210'),
  ('phone_alt', '+91 11 4567 8900'),
  ('email', 'info@sharmaconstruction.com'),
  ('email_careers', 'careers@sharmaconstruction.com'),
  ('address', '123 Main Street, Tughlakabad Institutional Area, New Delhi 110062, India'),
  ('hours', 'Mon - Sat, 9:00 AM - 6:00 PM'),
  ('facebook', 'https://www.facebook.com/'),
  ('instagram', 'https://www.instagram.com/'),
  ('linkedin', 'https://www.linkedin.com/'),
  ('whatsapp', 'https://wa.me/919876543210'),
  ('seo_title', 'Sharma Interior Construction | Building & Infrastructure Contractors'),
  ('seo_description', 'Sharma Interior Construction delivers residential, commercial, industrial and infrastructure projects across India. 10+ years, 1500+ completed projects.'),
  ('footer_text', 'A full-service construction contractor delivering residential, commercial, industrial and infrastructure projects across India.'),
  ('map_embed', 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3505.871796286783!2d77.2429713242177!3d28.513504689478324!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x390ce174a3adccd3%3A0xcea21e67b7cdb14b!2sNew%20Delhi!5e0!3m2!1sen!2sin!4v1742616755822!5m2!1sen!2sin'),
  ('seo_site_url', 'https://sharmaconstruction.com'),
  ('seo_default_image', 'homeback.jpg'),
  ('seo_keywords', 'construction company, building contractor, residential construction, commercial construction, industrial construction, civil contractor Delhi NCR'),
  ('seo_title_suffix', ' | Sharma Interior Construction'),
  ('seo_verification', ''),
  ('seo_bing_verification', ''),
  ('seo_twitter_handle', ''),
  ('seo_noindex_site', '0'),
  ('ga_measurement_id', ''),
  ('gtm_id', ''),
  ('biz_legal_name', 'Sharma Interior Construction'),
  ('biz_street', '123 Main Street, Tughlakabad Institutional Area'),
  ('biz_city', 'New Delhi'),
  ('biz_state', 'Delhi'),
  ('biz_postal', '110062'),
  ('biz_country', 'IN'),
  ('biz_lat', '28.5135'),
  ('biz_lng', '77.2430'),
  ('biz_price_range', '$$'),
  ('biz_founded', '2015'),
  ('biz_areas', 'New Delhi, Gurugram, Noida, Faridabad, Ghaziabad, Greater Noida'),
  ('biz_hours_spec', 'Mo-Sa 09:00-18:00'),
  ('biz_profile_url', '');

-- services (11 rows)
insert into public.services ("id", "slug", "title", "description", "icon", "image", "features", "sort", "active", "featured") values
  (1, 'building', 'Building Construction', 'Complete structures from foundation to finish - RCC frame, masonry, waterproofing, services and finishes under one contract.', '', 'images/service-1.png', '["Turnkey design-and-build option", "Structural and finishing packages", "Single point of accountability"]', 0, true, true),
  (2, 'residential', 'Residential Construction', 'Villas, apartment blocks and housing developments built for the way people actually live in them.', '', 'images/service-2.png', '["Independent villas and duplexes", "Multi-storey apartment blocks", "Gated community development"]', 1, true, true),
  (3, 'commercial', 'Commercial Construction', 'Offices, retail and hospitality built around your opening date and your operating hours.', '', 'images/service-3.png', '["Office towers and business parks", "Retail and showroom builds", "Phased works in occupied buildings"]', 2, true, true),
  (4, 'industrial', 'Industrial Construction', 'Factories, warehouses and process facilities engineered for heavy loads and hard use.', '', 'images/service-4.png', '["Pre-engineered steel buildings", "Heavy-duty industrial flooring", "Plant and utility coordination"]', 3, true, true),
  (5, 'civil', 'Civil Construction', 'Earthworks, foundations, retaining structures and the civil scope that everything else depends on.', '', 'images/service-5.png', '["Excavation and ground improvement", "Piling and deep foundations", "Retaining walls and drainage"]', 4, true, true),
  (6, 'infrastructure', 'Infrastructure Development', 'Roads, external services and site development delivered to public-sector specification.', '', 'images/service-6.png', '["Internal roads and pavements", "Stormwater and sewerage networks", "Site grading and external works"]', 5, true, true),
  (7, 'renovation', 'Renovation & Remodelling', 'Structural repair, extension and modernisation of buildings already in service.', '', 'images/service-7.png', '["Structural strengthening and repair", "Facade and roof replacement", "Change-of-use conversions"]', 6, true, false),
  (8, 'interior', 'Interior Construction', 'Fit-out that is detailed to be built, not just rendered - joinery, services, finishes and handover.', '', 'images/service-8.png', '["Corporate and retail fit-out", "Bespoke joinery and millwork", "MEP coordination and testing"]', 7, true, false),
  (9, 'pm', 'Project Management', 'Independent programme, cost and contract management when you are running your own trades.', 'ri-node-tree', '', '["Programme and milestone control", "Cost reporting and forecasting", "Contract and variation administration"]', 8, true, false),
  (10, 'engineering', 'Engineering Services', 'Design review, temporary works and value engineering by our in-house structural team.', 'ri-compasses-2-line', '', '["Structural design and review", "Temporary works design", "Value engineering studies"]', 9, true, false),
  (11, 'maintenance', 'Maintenance Services', 'Planned and reactive maintenance that keeps completed assets performing.', 'ri-tools-fill', '', '["Annual maintenance contracts", "Reactive repair callout", "Facade and waterproofing upkeep"]', 10, true, false);

-- projects (9 rows)
insert into public.projects ("id", "slug", "title", "location", "category", "status", "completion", "description", "image", "sort", "active", "featured") values
  (1, 'skyline-residency', 'Skyline Residency', 'Pune, Maharashtra', 'residential', 'completed', 'March 2025', 'A 14-storey residential tower with 96 units, twin basements and a podium amenity deck. Delivered three weeks ahead of programme.', 'images/project-1.jpg', 0, true, true),
  (2, 'meridian-corporate-park', 'Meridian Corporate Park', 'Bengaluru, Karnataka', 'commercial', 'completed', 'November 2024', 'Two office blocks totalling 180,000 sq ft including core-and-shell, facade and full MEP coordination.', 'images/project-2.jpg', 1, true, true),
  (3, 'northgate-logistics-hub', 'Northgate Logistics Hub', 'Delhi NCR', 'industrial', 'ongoing', 'Est. August 2026', 'A 240,000 sq ft pre-engineered warehouse with heavy-duty flooring, 42 dock levellers and an on-site substation.', 'images/project-3.jpg', 2, true, true),
  (4, 'grand-central-mall', 'Grand Central Mall', 'Gurugram, Haryana', 'commercial', 'completed', 'July 2024', 'Retail development with three trading levels, a food court and structured parking for 600 vehicles.', 'images/project-4.jpg', 3, true, true),
  (5, 'riverfront-development', 'Riverfront Development', 'Ranchi, Jharkhand', 'infrastructure', 'ongoing', 'Est. December 2026', 'Public riverfront works covering embankment protection, stormwater drainage, internal roads and landscaping.', 'images/project-5.jpg', 4, true, true),
  (6, 'harbour-view-villas', 'Harbour View Villas', 'Chennai, Tamil Nadu', 'residential', 'completed', 'January 2025', 'Eighteen independent villas with private plots, a shared clubhouse and full external infrastructure.', 'images/project-6.jpg', 5, true, true),
  (7, 'aster-medical-centre', 'Aster Medical Centre', 'New Delhi', 'commercial', 'completed', 'September 2024', 'A four-storey diagnostic and outpatient facility built to healthcare finish and hygiene standards.', 'cc.jpg', 6, true, false),
  (8, 'westline-industrial-estate', 'Westline Industrial Estate', 'Chennai, Tamil Nadu', 'industrial', 'ongoing', 'Est. May 2026', 'Site development and civil works for six industrial plots including roads, drainage and utility corridors.', 'site.jpg', 7, true, false),
  (9, 'civic-plaza-redevelopment', 'Civic Plaza Redevelopment', 'Gurugram, Haryana', 'infrastructure', 'completed', 'February 2024', 'Public plaza rebuild with new paving, underground services diversion, lighting and street furniture.', 'mall.jpg', 8, true, false);

-- team (6 rows)
insert into public.team ("id", "name", "role", "bio", "image", "linkedin", "email", "sort", "active") values
  (1, 'Vikram Sharma', 'Founder & Managing Director', 'Civil engineer with 22 years across high-rise residential and public infrastructure.', 'images/pic-1.png', 'https://www.linkedin.com/', 'info@sharmaconstruction.com', 0, true),
  (2, 'Anita Deshpande', 'Director, Operations', 'Runs programme, procurement and subcontractor performance across all live sites.', 'images/pic-2.png', 'https://www.linkedin.com/', 'info@sharmaconstruction.com', 1, true),
  (3, 'Rohit Nair', 'Head of Engineering', 'Structural design review, temporary works and value engineering.', 'images/pic-3.png', 'https://www.linkedin.com/', 'info@sharmaconstruction.com', 2, true),
  (4, 'Meera Iyer', 'Head of Quality & HSE', 'Owns the inspection regime, testing schedule and site safety audits.', 'images/pic-4.png', 'https://www.linkedin.com/', 'info@sharmaconstruction.com', 3, true),
  (5, 'Sanjay Gupta', 'Senior Project Manager', 'Delivers commercial and industrial packages from mobilisation to handover.', 'images/pic-5.png', 'https://www.linkedin.com/', 'info@sharmaconstruction.com', 4, true),
  (6, 'Kavita Reddy', 'Head of Interiors', 'Leads fit-out delivery, finishes coordination and client sign-off.', 'images/pic-6.png', 'https://www.linkedin.com/', 'info@sharmaconstruction.com', 5, true);

-- testimonials (4 rows)
insert into public.testimonials ("id", "name", "company", "quote", "rating", "image", "sort", "active") values
  (1, 'Rajesh Kumar', 'MD, Meridian Developers', 'They handed over three weeks early and the snag list was under twenty items across forty thousand square feet. That is unusual in this industry.', 5, 'images/pic-1.png', 0, true),
  (2, 'Priya Sharma', 'Project Head, Northgate Logistics', 'What impressed us was the documentation. Every pour, every test certificate, every variation was traceable. The audit was painless.', 5, 'images/pic-2.png', 1, true),
  (3, 'Anil Mehta', 'Director, Harbour Estates', 'We have used four contractors in ten years. Sharma is the only one we did not have to chase. The site was clean and the crew was disciplined.', 5, 'images/pic-3.png', 2, true),
  (4, 'Sunita Verma', 'CFO, Grand Central Retail', 'Costing was transparent from day one. No inflated variations at the end, which is exactly why we have given them our next two sites.', 5, 'images/pic-4.png', 3, true);

-- faqs (6 rows)
insert into public.faqs ("id", "question", "answer", "page", "sort", "active") values
  (1, 'What types of construction projects do you take on?', 'We deliver residential, commercial, industrial and infrastructure projects - from independent villas and apartment blocks through to factories, warehouses and public works. Any of these can be run as a turnkey design-and-build contract or as a structure-only or finishing package.', '/contact.html', 0, true),
  (2, 'Which areas do you work in?', 'Our primary service area is Delhi NCR - New Delhi, Gurugram, Noida, Faridabad, Ghaziabad and Greater Noida. We take projects elsewhere in India where the scope justifies mobilising a site team.', '/contact.html', 1, true),
  (3, 'How long does a construction project usually take?', 'An independent villa typically runs 8-14 months from foundation to handover; an apartment block or commercial fit-out runs 14-30 months depending on floor count and services. We issue a programme with milestone dates before work starts and report against it every month.', '/contact.html', 2, true),
  (4, 'How do you price a project?', 'We quote against a measured bill of quantities, not a rate per square foot. That takes longer to prepare but means the number you approve is the number you pay, barring scope changes you sign off yourself.', '/contact.html', 3, true),
  (5, 'Are you licensed and insured?', 'Yes. We carry contractor''s all-risk and third-party liability cover on every site, and our supervisors hold current safety certification. Documentation is available on request before contract signature.', '/contact.html', 4, true),
  (6, 'Do you handle approvals and drawings?', 'On turnkey contracts, yes - structural design, MEP coordination and the municipal approval trail are included. On structure-only contracts we build to the consultant''s drawings and coordinate with their team.', '/service.html', 5, true);

-- jobs (5 rows)
insert into public.jobs ("id", "title", "location", "experience", "employment", "description", "sort", "active", "created_at") values
  (1, 'Site Engineer (Civil)', 'New Delhi NCR', '3-6 years', 'Full time', 'Day-to-day execution, setting out, quality checks and subcontractor coordination on an active residential site. Diploma or B.E. in Civil Engineering required.', 0, true, '2026-08-06 17:55:26'),
  (2, 'Project Manager', 'Bengaluru', '8-12 years', 'Full time', 'Own programme, cost and client reporting for a commercial package. Proven record delivering 100,000+ sq ft builds end to end.', 1, true, '2026-08-06 17:55:26'),
  (3, 'Safety Officer (HSE)', 'Chennai', '2-5 years', 'Full time', 'Run inductions, toolbox talks, permits to work and incident reporting across two industrial sites. Recognised safety qualification required.', 2, true, '2026-08-06 17:55:26'),
  (4, 'Quantity Surveyor', 'New Delhi NCR', '4-8 years', 'Full time', 'Prepare BOQs, valuations and variation assessments. Strong measurement skills and familiarity with standard methods of measurement.', 3, true, '2026-08-06 17:55:26'),
  (5, 'Interior Site Supervisor', 'Gurugram', '3-5 years', 'Full time', 'Supervise joinery, finishes and MEP coordination on corporate fit-out projects. Snagging and handover experience essential.', 4, true, '2026-08-06 17:55:27');

-- page_seo (5 rows)
insert into public.page_seo ("route", "title", "description", "keyword", "og_title", "og_desc", "og_image", "canonical", "noindex", "nofollow", "changefreq", "priority", "updated_at") values
  ('/', 'Construction Company in Delhi NCR', 'Sharma Interior Construction builds residential, commercial and industrial projects across Delhi NCR. 10+ years, 1500+ projects delivered on programme.', 'construction company delhi ncr', '', '', '', '', false, false, 'weekly', '1.0', '2026-08-09 07:44:45'),
  ('/about.html', 'About Us - Our Story & Team', 'Ten years of building across Delhi NCR. Meet the engineers and site teams behind 1500+ completed residential, commercial and infrastructure projects.', 'construction company about', '', '', '', '', false, false, 'monthly', '0.7', '2026-08-09 07:44:45'),
  ('/service.html', 'Construction Services - Building & Civil Works', 'Building construction, residential and commercial projects, industrial sheds, interior fit-out, renovation and infrastructure works across Delhi NCR.', 'construction services delhi ncr', '', '', '', '', false, false, 'weekly', '0.9', '2026-08-09 07:44:45'),
  ('/project.html', 'Our Projects - Completed & Ongoing Work', 'Browse completed and ongoing construction projects across Delhi NCR - residential towers, commercial builds, industrial plants and public works.', 'construction projects delhi', '', '', '', '', false, false, 'weekly', '0.8', '2026-08-09 07:44:45'),
  ('/contact.html', 'Contact Us - Get a Free Project Quote', 'Talk to our estimating team about your construction project. Free measured quote, site visit across Delhi NCR, and a written programme before work starts.', 'construction company contact quote', '', '', '', '', false, false, 'monthly', '0.7', '2026-08-09 07:44:45');

-- media: no rows

-- redirects: no rows

-- keep identity columns from colliding with the imported ids
select setval(pg_get_serial_sequence('public.services', 'id'), coalesce((select max("id") from public.services), 1), true);
select setval(pg_get_serial_sequence('public.projects', 'id'), coalesce((select max("id") from public.projects), 1), true);
select setval(pg_get_serial_sequence('public.team', 'id'), coalesce((select max("id") from public.team), 1), true);
select setval(pg_get_serial_sequence('public.testimonials', 'id'), coalesce((select max("id") from public.testimonials), 1), true);
select setval(pg_get_serial_sequence('public.faqs', 'id'), coalesce((select max("id") from public.faqs), 1), true);
select setval(pg_get_serial_sequence('public.jobs', 'id'), coalesce((select max("id") from public.jobs), 1), true);
select setval(pg_get_serial_sequence('public.media', 'id'), coalesce((select max("id") from public.media), 1), true);
select setval(pg_get_serial_sequence('public.redirects', 'id'), coalesce((select max("id") from public.redirects), 1), true);

commit;
