#!/usr/bin/env python3
"""Generate supabase/schema.sql (Postgres DDL + current data) from data/site.db."""
import os
import sqlite3

BASE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(BASE, "data", "site.db")
OUT = os.path.join(BASE, "supabase", "schema.sql")

# users/sessions are replaced by Supabase Auth and deliberately not migrated.
BOOL_COLS = {"active", "featured", "noindex", "nofollow"}
TS_COLS = {"created_at", "updated_at"}

# table -> (primary key, ordered column list is taken from sqlite)
TABLES = ["settings", "services", "projects", "team", "testimonials",
          "faqs", "jobs", "page_seo", "media", "redirects"]

# Columns that are the identity PK in each table (None where the PK is natural)
IDENTITY = {"services": "id", "projects": "id", "team": "id",
            "testimonials": "id", "faqs": "id", "jobs": "id",
            "media": "id", "redirects": "id"}


def pg_type(table, col, decl):
    d = decl.upper()
    if col in BOOL_COLS:
        return "boolean"
    if col in TS_COLS:
        return "timestamptz"
    if IDENTITY.get(table) == col:
        return "bigint generated by default as identity primary key"
    if "INT" in d:
        return "integer"
    return "text"


def default_for(table, col, decl, notnull, dflt):
    if IDENTITY.get(table) == col:
        return ""
    parts = []
    if col in TS_COLS:
        parts.append("default now()")
    elif col in BOOL_COLS:
        parts.append("default %s" % ("true" if str(dflt).strip("'") == "1" else "false"))
    elif dflt is not None:
        parts.append("default %s" % dflt)
    if notnull:
        parts.append("not null")
    return " " + " ".join(parts) if parts else ""


def lit(value, col):
    if value is None:
        return "null"
    if col in BOOL_COLS:
        return "true" if value else "false"
    if isinstance(value, (int, float)):
        return str(value)
    return "'" + str(value).replace("'", "''") + "'"


def main():
    con = sqlite3.connect(SRC)
    con.row_factory = sqlite3.Row
    os.makedirs(os.path.dirname(OUT), exist_ok=True)

    out = []
    w = out.append
    w("-- Sharma Interior Construction - Supabase schema + content")
    w("-- Generated from data/site.db by tools/gen_supabase_schema.py")
    w("--")
    w("-- Paste this whole file into the Supabase SQL Editor and run it.")
    w("-- Safe to re-run: it drops and recreates the content tables.")
    w("-- Admin logins are NOT here - Supabase Auth handles those.")
    w("")
    w("begin;")
    w("")

    # ---- drop in reverse so a re-run is clean
    w("drop table if exists " + ", ".join(
        "public.%s" % t for t in reversed(TABLES)) + " cascade;")
    w("")

    uniques = {}
    for table in TABLES:
        cols = con.execute("PRAGMA table_info(%s)" % table).fetchall()
        # natural primary keys (settings.key, page_seo.route)
        pk = [c["name"] for c in cols if c["pk"] and IDENTITY.get(table) != c["name"]]

        # UNIQUE constraints declared in the original DDL
        ddl = con.execute(
            "SELECT sql FROM sqlite_master WHERE name=?", (table,)).fetchone()[0]
        uniq = [c["name"] for c in cols
                if ("%s " % c["name"]) in ddl and "UNIQUE" in
                ddl.split(c["name"], 1)[1].split("\n", 1)[0].upper()]
        uniques[table] = uniq

        lines = []
        for c in cols:
            t = pg_type(table, c["name"], c["type"])
            d = default_for(table, c["name"], c["type"], c["notnull"], c["dflt_value"])
            u = " unique" if c["name"] in uniq else ""
            lines.append('  "%s" %s%s%s' % (c["name"], t, d, u))
        if pk:
            lines.append("  primary key (%s)" % ", ".join('"%s"' % p for p in pk))

        w("create table public.%s (" % table)
        w(",\n".join(lines))
        w(");")
        w("")

    # ---- data
    w("-- ------------------------------------------------------------------")
    w("-- content")
    w("-- ------------------------------------------------------------------")
    w("")
    total = 0
    for table in TABLES:
        rows = con.execute("SELECT * FROM %s" % table).fetchall()
        if not rows:
            w("-- %s: no rows" % table)
            w("")
            continue
        names = rows[0].keys()
        w("-- %s (%d rows)" % (table, len(rows)))
        w("insert into public.%s (%s) values" % (
            table, ", ".join('"%s"' % n for n in names)))
        vals = [",\n".join(
            "  (%s)" % ", ".join(lit(r[n], n) for n in names) for r in rows)]
        w(vals[0] + ";")
        w("")
        total += len(rows)

    # ---- identity sequences must skip past the ids we just inserted
    w("-- keep identity columns from colliding with the imported ids")
    for table, col in IDENTITY.items():
        w("select setval(pg_get_serial_sequence('public.%s', '%s'), "
          "coalesce((select max(\"%s\") from public.%s), 1), true);" %
          (table, col, col, table))
    w("")
    w("commit;")
    w("")

    with open(OUT, "w") as fh:
        fh.write("\n".join(out))

    print("  wrote %s" % OUT)
    print("  tables: %d   rows: %d" % (len(TABLES), total))
    for t in TABLES:
        n = con.execute("SELECT COUNT(*) FROM %s" % t).fetchone()[0]
        print("    %-14s %3d rows%s" % (
            t, n, "   unique: " + ",".join(uniques[t]) if uniques[t] else ""))


if __name__ == "__main__":
    main()
